services:
  - type: web
    name: your-service-name
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y python3-pyaudio
      pip install -r requirements.txt
    startCommand: python your_app.py
